version: '4.10'
services:
  db:
    image: 'postgres:14'
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data      
    environment:
      POSTGRES_PASSWORD: '7859'
      POSTGRES_USER: 'postgres'
    networks:
      - backend
    env_file:
      - ./.env
  server:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: ./server
    restart: unless-stopped
    volumes:
      - /server/node_modules
    ports:
      - 5000:5000
    networks:
      - backend
      - frontend
    env_file:
      - ../.env
  client:
    depends_on:
      - server
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 4000:3000
    volumes:
      - /client/node_modules
    stdin_open: true
    networks:
      - frontend
volumes:
  db:
networks:
  backend:
  frontend: