version: '4.10'
services:
  db:
    image: 'postgres:14'
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data      
    environment:
      POSTGRES_PASSWORD: '7859'
      POSTGRES_USER: 'postgres'
    networks:
      - backend

  server:
    depends_on:
      - db
    build: ./server
    restart: unless-stopped
    ports:
      - 5000:5000
    networks:
      - backend
      - frontend
  client:
    depends_on:
      - server
    build:
      context: ./client
    ports:
      - 3000:3000
    volumes:
      - /node_modules
    stdin_open: true
    networks:
      - frontend
volumes:
  db:
networks:
  backend:
  frontend: